#sudo: false
sudo: required
dist: trusty
language: c

before_install:
  - sudo mkdir -p /etc/nix
  - sudo sh -c 'echo "build-max-jobs = 4" >> /etc/nix/nix.conf'
  - sudo sh -c 'echo "build-users-group =" >> /etc/nix/nix.conf'
  - bash <(curl -sSL https://nixos.org/nix/install)
  - source $HOME/.nix-profile/etc/profile.d/nix.sh

  #- bash <(curl -sSL https://github.com/robbinch/travis-nix-proot/raw/master/install)
  # - export PATH=$HOME/.travis-nix-proot/bin:$PATH
  - export TINC_USE_NIX=yes
  # - travis-nix-proot setup

install:
  - nix-env -i bats
  - nix-env -i bc
  - nix-env -i cabal-install

  # - travis-nix-proot nix-env -i bats
  # - travis-nix-proot nix-env -i bc
  # - travis-nix-proot nix-env -i cabal-install

before_script:
  - cabal sdist
  - nix-env -iA haskellPackages.tinc -f '<nixpkgs>'
  - mkdir -p $HOME/.tinc
  - ln -s $PWD/plugins $HOME/.tinc/
  - cabal update
  - tinc install

  # - travis-nix-proot cabal sdist
  # - travis-nix-proot nix-env -i tinc -f default.nix
  # - ln -s $PWD/plugins $HOME/.tinc/

script:
  - travis_wait 50 bats acceptance/run_tests.sh

  # - travis_wait 50 travis-nix-proot bats acceptance/run_tests.sh

# before_cache:
#   - travis-nix-proot gc
#   - travis-nix-proot dump-db

# cache:
#   directories:
#     - $HOME/.tinc/cache
#     - /nix
#     - $HOME/travis-nix-proot.cache
